// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zvcWiWge7MtwLMN50R4tJVTSZ5dgIwY',
    appId: '1:802635202251:android:84066464baf8d44947654e',
    messagingSenderId: '802635202251',
    projectId: 'detailing-pro',
    storageBucket: 'detailing-pro.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XG97zUU2JlOWjN336-rEgP03UQBeWTY',
    appId: '1:802635202251:web:6888cf2faf8d44d847654e',
    messagingSenderId: '802635202251',
    projectId: 'detailing-pro',
    authDomain: 'detailing-pro.firebaseapp.com',
    storageBucket: 'detailing-pro.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XG97zUU2JlOWjN336-rEgP03UQBeWTY',
    appId: '1:802635202251:web:6888cf2faf8d44d847654e',
    messagingSenderId: '802635202251',
    projectId: 'detailing-pro',
    authDomain: 'detailing-pro.firebaseapp.com',
    storageBucket: 'detailing-pro.firebasestorage.app',
  );

}